# Generated by Django 5.2.6 on 2025-09-15 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='contacto',
        ),
    ]
