# Generated by Django 5.2.5 on 2025-08-21 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_uniforme_categoria'),
    ]

    operations = [
    ]
