# Generated by Django 5.2.5 on 2025-08-28 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20250821_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='no_recibo',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
