# Generated by Django 4.2.25 on 2025-11-02 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_detalleventa_producto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
