# Generated by Django 5.2.6 on 2025-09-12 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_venta_no_recibo'),
        ('clientes', '0006_cliente_codigo_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='cliente_id',
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='clientes.cliente'),
        ),
    ]
