# Generated by Django 4.2.25 on 2025-11-05 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniforme',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
