# Generated by Django 4.2.27 on 2026-01-26 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_uniforme_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='anticipo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='pedido',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('proceso', 'En proceso'), ('cerrado', 'Cerrado'), ('cancelado', 'Cancelado')], default='proceso', max_length=10),
        ),
    ]
