# Generated by Django 4.2.27 on 2026-01-27 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_pedido_anticipo_pedido_descripcion_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='anticipo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
