# Generated by Django 5.2.1 on 2025-05-27 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_remove_proveedor_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='descripcion',
            field=models.TextField(default='Sin descripcion'),
            preserve_default=False,
        ),
    ]
