# Generated by Django 5.2.1 on 2025-05-27 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_compra_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='descripcion',
            field=models.TextField(default=''),
        ),
    ]
