# Generated by Django 5.2.4 on 2025-07-24 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_proveedor_contacto_alter_cliente_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='codigo_cliente',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True),
        ),
    ]
